# Generated by Django 3.1 on 2021-02-19 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('image', models.ImageField(default='1', upload_to='slide')),
                ('image1', models.ImageField(default='1', upload_to='slide')),
                ('image2', models.ImageField(default='1', upload_to='slide')),
                ('imagecote', models.ImageField(default='1', upload_to='slide')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('numero', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcour', models.CharField(max_length=200)),
                ('doc', models.FileField(upload_to='')),
                ('image_cour', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomfaculte', models.CharField(default=0, max_length=500)),
                ('descriptionfact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('titre', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nommatiere', models.CharField(default=0, max_length=100)),
                ('cour', models.ManyToManyField(related_name='cour', to='bvci.Cour')),
            ],
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomniveau', models.CharField(default=0, max_length=90)),
                ('matiere', models.ManyToManyField(related_name='matieres', to='bvci.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=0, max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('slug', models.CharField(default=0, max_length=100)),
                ('departement', models.ManyToManyField(related_name='departements', to='bvci.Departement')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='niveau',
            field=models.ManyToManyField(related_name='niveaux', to='bvci.Niveau'),
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='actualite')),
                ('descriprion', models.TextField()),
                ('detail_Actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvci.detail_actualite')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvci.universite')),
            ],
        ),
    ]
